Iter13
zhenyanesterkova/metricsmonitor pull request #14
Opened 2024-12-04 00:27 UTC by zhenyanesterkova

2024-12-04 20:16 UTC, s-shpak requested changes

2024-12-04 20:16 UTC, s-shpak commented on internal/app/agent/sender/sender.go
> +	Report                  ReportData
Мне кажется, что не все поля здесь необходимо экспортировать

2024-12-04 20:16 UTC, s-shpak commented on internal/app/agent/sender/sender.go
> +		log.Printf("    no data for sending ...")
```suggestion
		log.Print("    no data for sending ...")
```

2024-12-04 20:16 UTC, s-shpak commented on internal/app/agent/sender/sender.go
> +			log.Printf("send failed ...")
Это логирование не нужно, т.к. в случае ошибки, она будет проброшена наверх

2024-12-04 20:16 UTC, s-shpak commented on internal/app/agent/sender/sender.go
> +			log.Printf("an error occurred while sending the report to the server %v", err)
Если здесь произошла ошибка, то сбрасывать счетчик не нужно

2024-12-04 20:16 UTC, s-shpak commented on internal/app/server/config/db.go
> +	MemStorageType         = "memory"
Если ты задаешь набор типов, то это лучше делаить через iota (аналог enum в go): https://yourbasic.org/golang/iota/

Но не очень ясно, зачем вообще прокидывать тип, можно прокидывать объекты конфигурации для всех БД, но все, кроме конфигурации используемой, будут равны `nil`

2024-12-04 20:16 UTC, s-shpak commented on internal/app/server/config/envconfigbuilder.go
> +		log.Printf("env:DATABASE_DSN=%s", dsn)
Так точно делать не надо: DSN -- строка с секретом, она не должна попадать в лог

2024-12-04 20:16 UTC, s-shpak commented on internal/storage/postgres/migrations/00002_add_index.up.sql
Я бы использовал здесь одну миграцию, т.к. все действия из двух мигрпаций сейчас приводят БД к одной версии

2024-12-04 20:16 UTC, s-shpak commented on internal/storage/postgres/postgres.go
> +			RETURNING *;
Не используй в коде `*`: всегда описывай явно, какие колонки ты хочешь вернуть -- это защитит тебя от потенциальной ошибки, если в таблице появятся новые колонки, а ты забудешь поменять парсинг ответа

2024-12-04 20:16 UTC, s-shpak commented on internal/storage/postgres/postgres.go
По-моему по зданию механизм ретраев должен работать и для БД. Попробуй подумать, как написать его так, чтобы переиспользовать этот функционал в каждой функции

2024-12-05 16:36 UTC, zhenyanesterkova commented on internal/app/agent/sender/sender.go
> +		log.Printf("    no data for sending ...")
Сделано

2024-12-05 16:46 UTC, zhenyanesterkova commented on internal/app/agent/sender/sender.go
> +			log.Printf("an error occurred while sending the report to the server %v", err)
Сделано

2024-12-05 17:45 UTC, zhenyanesterkova commented on internal/app/server/config/db.go
> +	MemStorageType         = "memory"
Сделано - теперь структура DataBaseConfig содержит указатели на две структуры - PostgresConfig и FileStorageConfig
Хранилище создается в зависимости от того, какой указатель не nil. 
Или memory по дефолту

2024-12-05 17:46 UTC, zhenyanesterkova commented on internal/app/server/config/envconfigbuilder.go
> +		log.Printf("env:DATABASE_DSN=%s", dsn)
Сделано - убрала лог переменных окружения

2024-12-05 19:40 UTC, zhenyanesterkova commented on internal/storage/postgres/postgres.go
> +			RETURNING *;
Сделано

2024-12-09 13:47 UTC, s-shpak requested changes

2024-12-09 13:47 UTC, s-shpak commented on internal/app/agent/sender/sender.go
> +	wGroup     *sync.WaitGroup
Я бы не стал добавлять `WaitGroup` cюда: она используется внешним компонентом, а не этим. Я бы запускал сендера выше, в отдельной горутине и в анонимной функции, а после его завершения вызывал бы `wg.Done()` (также выше)

2024-12-09 13:47 UTC, s-shpak commented on internal/app/agent/statistic/statistic.go
> +	wg *sync.WaitGroup,
См. комментарий выше

2024-12-09 13:47 UTC, s-shpak commented on internal/handler/handler.go
> +	Ping() (bool, error)
Здесь можно просто возвращать ошибку. `nil` будет указывать на то, что хранилище получилось пингануть

2024-12-09 13:47 UTC, s-shpak commented on internal/storage/filestorage/filestorage.go
> +		return false, errors.New("filestorage is not initialized")
А в каком случае это может произойти ? Кажется, что если объект существует, то он полностью инициализирован

2024-12-09 13:47 UTC, s-shpak commented on internal/storage/postgres/postgres.go
> +	} else if typeMetric == metric.TypeCounter {
Здесь код можно сделать более плоским

2024-12-09 13:47 UTC, s-shpak commented on internal/storage/postgres/postgres.go
> +			err = storagerror.NewRetriableError(err)
Мне не очень нравится такой дизайн: Postgres почему-то знает о том, что существуют `Retriable errors`. Я бы делал это по-другому: насторой проверку на уровне `retrystorage`. Это может быть обычный предикат, который передается внутрь `retrystorage` при его инициалзации, и который принимает ответ постгреса в качестве аргмуента. Тогда `retrystorage` будет настоящей оберткой над хендлером к постгресу

2024-12-10 08:24 UTC, zhenyanesterkova commented on internal/app/agent/sender/sender.go
> +	wGroup     *sync.WaitGroup
+

2024-12-10 08:24 UTC, zhenyanesterkova commented on internal/app/agent/statistic/statistic.go
> +	wg *sync.WaitGroup,
\+

2024-12-10 08:39 UTC, zhenyanesterkova commented on internal/handler/handler.go
> +	Ping() (bool, error)
\+

2024-12-10 08:39 UTC, zhenyanesterkova commented on internal/storage/filestorage/filestorage.go
> +		return false, errors.New("filestorage is not initialized")
\+

2024-12-10 09:29 UTC, zhenyanesterkova commented on internal/storage/postgres/postgres.go
> +	} else if typeMetric == metric.TypeCounter {
\+

2024-12-10 10:07 UTC, zhenyanesterkova commented on internal/storage/postgres/postgres.go
> +			err = storagerror.NewRetriableError(err)
\+

2024-12-10 13:33 UTC, s-shpak approved these changes

2024-12-11 16:30 UTC, merged