Iter15
zhenyanesterkova/metricsmonitor pull request #16
Opened 2024-12-17 07:46 UTC by zhenyanesterkova

2024-12-17 22:33 UTC, s-shpak requested changes

2024-12-17 22:33 UTC, s-shpak commented on internal/app/agent/metric/metricbuffer.go
> +	mutex   *sync.RWMutex
А мы не обсуждали `RWMutex` в прошлых ревью ?

В данном случае лучше использовать обычный, т.к. с `RWMutex` твое приложение, скорее всего, будет работать медленее. `RWMutex` можно исползовать если количество записей на порядки превышает количество чтений, и его воздействие на быстродействие приложения стоит проверять при помощи бенчмаркинга

2024-12-17 22:33 UTC, s-shpak commented on internal/middleware/signdata.go
> +				log.Errorf("middleware: CheckSignData - failed read body: %v", err)
Штатные ошибки не надо логировать

2024-12-17 22:33 UTC, s-shpak commented on internal/app/agent/sender/sender.go
> +func (s *Sender) SendReport() {
Т.к. ты делаешь graceful shutdown в main, добавь остановку всех горутин при остановке сервиса

2024-12-18 05:29 UTC, zhenyanesterkova commented on internal/app/agent/metric/metricbuffer.go
> +	mutex   *sync.RWMutex
Спасибо, поняла, исправила. В прошлом ревью мы обсуждали, что я использовала Mutex не там, где необходимо. RWMutex я только здесь добавила.

2024-12-18 05:49 UTC, zhenyanesterkova commented on internal/middleware/signdata.go
> +				log.Errorf("middleware: CheckSignData - failed read body: %v", err)
Исправила

2024-12-18 12:43 UTC, zhenyanesterkova commented on internal/app/agent/sender/sender.go
> +func (s *Sender) SendReport() {
Сделала

2024-12-23 01:33 UTC, s-shpak approved these changes

2024-12-26 17:26 UTC, merged