Iter9
zhenyanesterkova/metricsmonitor pull request #9
Opened 2024-11-05 15:31 UTC by zhenyanesterkova

2024-11-20 13:14 UTC, s-shpak commented on cmd/agent/main.go
>  	var mutex sync.Mutex
Мьютекс должен использоваться только тем объектом, в котором он определен. Потому, если ты хочешь защитить им локальное хранилище агента, я бы советовал создать новую структуру, которая объединяла бы in-memory хранилище и мьютекс, а конкурентно-безопасный доступ к хранилищу осуществлялся бы через методы этой структуры

2024-11-20 13:17 UTC, s-shpak commented on cmd/agent/main.go
> +const goroutinesCount = 2
Не очень хорошо определять количество воркеров так: ты можешь забыть обновить это значение, если появятся новые горутины. Лучше после каждого запуска горутины вызывать `wg.Add(1)`

2024-11-20 13:20 UTC, s-shpak commented on go.mod
`go.mod` надо обновить, чтобы не забывать это делать, можно настроить гит-хук для этого. Здесь можно посмотреть, как это делается: https://github.com/s-shpak/yabinar-best-practices/blob/main/scripts/pre-commit.sh

2024-11-20 13:22 UTC, s-shpak commented on internal/app/agent/config/envbuilder.go
> +func (c *Config) ReadEnv() {
Кажется, что в этом пакете необходимо экспортировать только `Build()`

2024-11-20 13:23 UTC, s-shpak commented on cmd/server/main.go
> +		os.Exit(1)
Это можно заменить на `log.Fatalf`

2024-11-20 13:23 UTC, s-shpak commented on cmd/server/main.go
> +		fmt.Printf("can not build config: %v", err)
Не используй `fmt.Printf`, используй пакет `log` до инициализации кастомного логгера, а после -- только кастомный логгер

2024-11-20 13:24 UTC, s-shpak commented on cmd/server/main.go
> +		loggerInst.LogrusLog.Errorf("can not parse log level: %v", err)
Здесь лучше вернуть ошибку и завершить работу приложения: если при иницализации сервиса возникла ошибка, то лучше fail early

2024-11-20 13:26 UTC, s-shpak commented on cmd/server/main.go
> +	fileWriter, err := rwfile.NewFileWriter(cfg.RConfig.FileStoragePath)
Лучше инкапсулировать логику работы с файлом в отдельный тип хранилища. Здесь я описал как: https://app.pachca.com/chats/15060382?message=380573810

Пожалуйста, напиши в пачку, если по этому предложению останутся какие-либо вопросы

2024-11-20 13:28 UTC, s-shpak commented on internal/app/agent/config/config.go
> +	pollIntervalFl    *int
Я понимаю, почему ты использовала указатели здесь, но я не уверен, что нам нужна информация определено ли поле или нет. Мы можем просто использовать значение по умолчанию, если поле не было явно сконфигурировано при инициализации

2024-11-20 13:29 UTC, s-shpak commented on internal/app/agent/metric/metric.go
> +		return fmt.Sprint(m.val)
Для преобразования числа в строку (и обратно) лучше использовать `strconv`: `fmt.Sprintf` будет работать намного медленее

2024-11-20 13:34 UTC, s-shpak commented on internal/app/agent/metric/metric.go
> +	refValue := reflect.ValueOf(m.val)
В принципе, использование рефлексии сократит количество кода. Пробема в том, что рефлексия будет работать намного медленее, чем подход, который ты использовала раньше (когда захардкодила имена полей). Т.к. этот код выполняется внутри хендлеров, его лучше сразу делать эффективным. Потому я рекомендую тебе вернуться к предыдущему подходу

2024-11-20 13:42 UTC, s-shpak commented on internal/app/agent/sender/sender.go
> +		s.Report.Mutex.Lock()
То, о чем я писал ранее: хорошей практикой будет хранение мьютекса как неэкспортируемого поля, и его использование только этой структурой

2024-11-20 13:42 UTC, s-shpak commented on internal/app/agent/sender/sender.go
> +			log.Printf("an error occurred while preparing the data for sending to the server %v", err)
Можно ли продолжать выполнение кода после этой ошибки ?

2024-11-20 13:44 UTC, s-shpak commented on internal/app/server/config/envconfigbuilder.go
> +	envEndpoint := os.Getenv("ADDRESS")
Лучше использовать https://pkg.go.dev/os#LookupEnv , чтобы различать пустую и невыставленную переменную окружения

2024-11-20 13:45 UTC, s-shpak commented on internal/app/server/mycompress/gzip.go
> +	R  io.ReadCloser
Это тоже можно сделать неэкспортируемыми полями

2024-11-20 13:46 UTC, s-shpak commented on internal/handler/get.go
> +		http.Error(w, "error get metrics: "+err.Error(), http.StatusInternalServerError)
1. Штатные ошибки (т.е. те ошибки, которые приводят к ответу клиенту с кодом 4**) не нужно логировать: они произошли "по вине" клиента и будут только замусоривать лог. А вот ошибки 5** нужно логировать обязательно

2. В случае нештатной ошибки, нельзя посылать детали о ней пользователю, т.к. это угроза безопасности приложения.

2024-11-22 05:30 UTC, zhenyanesterkova commented on cmd/agent/main.go
> +const goroutinesCount = 2
Исправлено

2024-11-22 05:36 UTC, zhenyanesterkova commented on cmd/agent/main.go
>  	var mutex sync.Mutex
Вынесла мьютекс в структуру MetricBuf в пакете metric, которая содержит хранилище метрик - Metrics. Для этой структуры определены методы, которые в нужный момент блокируют доступ к ресурсу. Правильно ли я поняла, что нужно было сделать?

2024-11-22 05:47 UTC, zhenyanesterkova commented on internal/app/agent/sender/sender.go
> +			log.Printf("an error occurred while preparing the data for sending to the server %v", err)
Здесь мысль была такая, что произошла ошибка отправки метрики на сервер, но мы можем продолжать ее обновлять и актуальное значение отправить в следующей итерации. Однако, получается, что какое-то время на сервере будет не актуальное состояние метрик, получается, здесь лучше все же завершить работу?

2024-11-22 09:41 UTC, zhenyanesterkova commented on internal/app/agent/metric/metric.go
> +		return fmt.Sprint(m.val)
Сделано

2024-11-22 09:42 UTC, zhenyanesterkova commented on internal/app/agent/metric/metric.go
> +	refValue := reflect.ValueOf(m.val)
Сделано

2024-11-22 13:39 UTC, zhenyanesterkova commented on go.mod
Гит-хук настроен

2024-11-22 13:49 UTC, zhenyanesterkova commented on internal/app/agent/config/envbuilder.go
> +func (c *Config) ReadEnv() {
Исправлено

2024-11-22 14:33 UTC, zhenyanesterkova commented on cmd/server/main.go
> +		os.Exit(1)
Сделано

2024-11-22 14:33 UTC, zhenyanesterkova commented on cmd/server/main.go
> +		loggerInst.LogrusLog.Errorf("can not parse log level: %v", err)
Сделано

2024-11-22 14:35 UTC, zhenyanesterkova commented on cmd/server/main.go
> +		fmt.Printf("can not build config: %v", err)
Сделано

2024-11-22 15:16 UTC, zhenyanesterkova commented on internal/app/agent/sender/sender.go
> +			log.Printf("an error occurred while preparing the data for sending to the server %v", err)
Сделано

2024-11-22 15:32 UTC, zhenyanesterkova commented on internal/app/server/config/envconfigbuilder.go
> +	envEndpoint := os.Getenv("ADDRESS")
Сделано

2024-11-26 14:48 UTC, zhenyanesterkova commented on internal/app/server/mycompress/gzip.go
> +	R  io.ReadCloser
Сделано

2024-11-26 15:35 UTC, zhenyanesterkova commented on internal/handler/get.go
> +		http.Error(w, "error get metrics: "+err.Error(), http.StatusInternalServerError)
Сделано

2024-11-27 07:51 UTC, zhenyanesterkova commented on internal/app/agent/config/config.go
> +	pollIntervalFl    *int
Переработала логику построения конфига, получилось вообще без использования дополнительных полей

2024-11-27 10:35 UTC, zhenyanesterkova commented on cmd/server/main.go
> +	fileWriter, err := rwfile.NewFileWriter(cfg.RConfig.FileStoragePath)
Сделано

2024-11-29 00:12 UTC, s-shpak requested changes
Не резолвь, пожалуйста, мои комментарии: мне нужно видеть, что именно мы обсуждали в повторном ревью. Если тебе хочется как-то трекать исправленные замечания, выставляй, например, реакции к комментариям

2024-11-29 00:12 UTC, s-shpak commented on internal/app/agent/metric/metricbuffer.go
> +	mutex   sync.Mutex
Правильно хранить указатель на мьютекс, а не сам мьютекс -- мьютекс нельзя копировать после инициализации. Почему это так мы, возмжно, разберем во второй части курса, пока это правило лучше просто запомнить

2024-11-29 00:12 UTC, s-shpak commented on internal/app/agent/metric/metricbuffer.go
> +	buf.Unlock()
Вызывать `Unlock` лучше при помощи `defer` сразу после вызова `Lock` (если это возможно): это позволяет не забыть вызвать `Unlock` в одной из ветвей исполнения

2024-11-29 00:12 UTC, s-shpak commented on internal/app/agent/metric/metricbuffer.go
> +func (buf *MetricBuf) Lock() {
`Lock`-`Unlock` мьютекса не надо вызывать извне. Если тебе надо вызвать какое-то действие конкуренто безопасным образом, определи для него метод (в котором используется мьютекс), и вызывай его

2024-11-29 05:32 UTC, zhenyanesterkova commented on internal/app/agent/metric/metricbuffer.go
> +	mutex   sync.Mutex
Исправила

2024-11-29 05:32 UTC, zhenyanesterkova commented on internal/app/agent/metric/metricbuffer.go
> +	buf.Unlock()
Исправила

2024-11-29 05:33 UTC, zhenyanesterkova commented on internal/app/agent/metric/metricbuffer.go
> +func (buf *MetricBuf) Lock() {
Исправила

2024-11-29 12:47 UTC, s-shpak approved these changes

2024-11-29 13:02 UTC, merged